#pragma once

extern PFN_vkCmdBeginRenderingKHR VKCmdBeginRenderingKHR;
extern PFN_vkCmdEndRenderingKHR VKCmdEndRenderingKHR;
extern PFN_vkSetDebugUtilsObjectNameEXT VKSetDebugUtilsObjectNameEXT;
extern PFN_vkCmdPipelineBarrier2KHR VKCmdPipelineBarrier2KHR;
extern PFN_vkCmdPushDescriptorSetKHR VKCmdPushDescriptorSetKHR;
extern PFN_vkCmdBeginDebugUtilsLabelEXT VKCmdBeginDebugUtilsLabelEXT;
extern PFN_vkCmdEndDebugUtilsLabelEXT VKCmdEndDebugUtilsLabelEXT;

namespace niji
{
void load_vulkan_function_pointers(VkDevice device);
}
